### PR TITLE
Adds a quick-reference Apollo Optics example

### PR DESCRIPTION
**Pull request by Siyfion**

### CODE REVIEW

**Comment by pcarrier** [comment]
@Siyfion Thanks a lot for that! We'll probably want to move that to an integration section in the docs but that gets us started.

**Comment by Siyfion** [comment]
Yeah, I thought as much, perhaps even into the Meteor Guide (Apollo Section) but still... as you say, it's a start!

**Comment by lorensr** [comment]
Thanks, I'd like to keep docs here: http://dev.apollodata.com/core/meteor.html

Would you like to add this to the bottom of that page, or shall I?

**Comment by Siyfion** [comment]
Please go ahead!

**Comment by lorensr** [comment]
Added 😊

https://github.com/apollostack/core-docs/blob/master/source/meteor.md#apollo-optics

**Pull request closed without merging**
