### PR TITLE
Always run /graphql on Meteor's default port.

### PR DESCRIPTION
**Pull request by timbrandin**
Refererence: apollostack/docs#104

### CODE REVIEW

**Comment by tomitrescak** [comment]
Does this mean that express is no longer running in a separate node process but in proc with Meteor?

**Comment by timbrandin** [comment]
@tomitrescak I believe it has always been in the same process even though you make it listen to another port. Correct me if I'm wrong @stubailo

**Comment by tomitrescak** [comment]
Hmm, I had two node processes running when running Apollo, killed Apollo one was immediately reinitiated by Meteor process.

**Comment by timbrandin** [comment]
This is new for me, your are right, there is two node processes with or without this PR. And yeah it restarts if you force quit it from the activity monitor.

**Comment by timbrandin** [comment]
But wait, I'm not sure if this is actually related to having express or not, it still seems to use two node processes.

**Comment by tomitrescak** [comment]
Interesting. I always figured it's the express process.

**Comment by timbrandin** [comment]
Maybe it's some other package I have, need to check in a clean project.

**Comment by timbrandin** [comment]
I just confirmed a clean meteor project using version 1.3.2.4 does start two node processes, so can we get this merged? 👍

**Comment by stubailo** [comment]
Meteor runs two processes so that the meteor tool doesn't crash if your app code does!

**Comment by stubailo** [comment]
I'm not the primary maintainer of this library, but this looks good to merge to me!

**Comment by stubailo** [comment]
@timbrandin this should include a change to the README: https://github.com/apollostack/meteor-integration#usage

**Comment by timbrandin** [comment]
yeah, you're absolutely right!

**Comment by tomitrescak** [comment]
There should be something about Apollos Redux store in the documentation. It's in all samples, but here I don't see it. Would be great to have it there.

**Comment by stubailo** [comment]
I am pretty sure that is at the top of the react integration page.

**Comment by lorensr** [comment]
Thanks Tim. 

A single process can listen on multiple ports. 

Is there a common reason why someone would want to put it on a different port? In which case we could leave in support for a port config param

**Comment by stubailo** [comment]
Ok so I realized why this works now - it's because express GraphQL added support for connect recently, but before it only supported express. Running everything on one port is much better, so this is a good idea for sure.

**Pull request merged**
