### PR TITLE
Fix when no auth header present

### PR DESCRIPTION
**Pull request by nicolaslopezj**
When there was none auth header present, the context would leave the same ```userId``` even if the client is in other device.

I'm working on a create-react-app app with a Meteor backend, only graphql connection, no ws. I'm using meteor accounts through graphql

### CODE REVIEW

**Comment by lorensr** [comment]
Hey, thank you so much for finding & reporting this! I just published `v0.1.1` – can you update & verify that it's fixed for you? 

I think the bug was when you pass an options object with a context – we were mutating that context. 

Couple issues with your change were `options.context` could be undefined, and conceivably someone could be doing their own auth in `givenOptions(req)` and using `context.userId`.

**Comment by nicolaslopezj** [comment]
I'm not sure this solves the problem.

I don't know why but the context is kept from one query to another (including other clients queries). 

So if we don't set the new ```context.userId``` we should unset the old one.

I was logged in to the graphql meteor server in the pc and in my phone I had the same ```context.userId``` without loggin in.

**Comment by lorensr** [comment]
Could you paste in the diff between https://github.com/apollostack/meteor-integration/tree/v0.1.1 and your code?

**Comment by nicolaslopezj** [comment]
In this part

```js
// Get the token from the header
if (req.headers.authorization) {
  const token = req.headers.authorization;
  check(token, String);
  const hashedToken = Accounts._hashLoginToken(token);

  // Get the user from the database
  user = await Meteor.users.findOne(
    {"services.resume.loginTokens.hashedToken": hashedToken},
    {fields: {
      _id: 1,
      'services.resume.loginTokens.$': 1
    }});

  if (user) {
    const expiresAt = Accounts._tokenExpiration(user.services.resume.loginTokens[0].when);
    const isExpired = expiresAt < new Date();

    if (!isExpired) {
      if (options.context) {
        // don't mutate the context provided in options
        options.context = Object.assign({}, options.context);
      } else {
        options.context = {};
      }

      options.context.userId = user._id;
    } else {
       /*Set the context.userId to null because it takes the last one*/
    }
  } else {
     /*Set the context.userId to null because it takes the last one*/
  }
} else {
  /*Set the context.userId to null because it takes the last one*/
}
```

Sorry I don't know if I'm explaining well.

The problem is:

Logged in Person 1 makes a call:

- ```context.userId``` is ```person1UserId```

Not logged in Person 2 makes a call:

- ```context.userId``` is ```person1UserId```

Logged in Person 3 makes a call:

- ```context.userId``` is ```person3UserId```

Not logged in Person 2 makes a call:

- ```context.userId``` is ```person3UserId```

**Comment by lorensr** [comment]
> Not logged in Person 2 makes a call:

Person 2 should get a new options object because of this line:

`options = Object.assign({}, defaultOptions, options);`
https://github.com/apollostack/meteor-integration/blob/v0.1.1/main-server.js#L46

and it should include an unmodified context because of this line:

`options.context = Object.assign({}, options.context);`
https://github.com/apollostack/meteor-integration/blob/v0.1.1/main-server.js#L46

**Comment by nicolaslopezj** [comment]
But if:

- ```req.headers.authorization``` is ```false```
- ```user``` is ```false``` 
- ```isExpired``` is ```true```

```options.context = Object.assign({}, options.context);``` never gets executed and the ```userId``` is not "reseted"

**Comment by lorensr** [comment]
> never gets executed

That's true, but line 46 runs again.

> Logged in Person 1 makes a call:

`options = Object.assign({}, defaultOptions, options);`
```
givenOptions = { context: {} }
options = { context: {} }
```
then:
` options.context.userId = user._id;`
```
options = { context: { userId: 'user1' } } 
```

> Not logged in Person 2 makes a call:

`options = Object.assign({}, defaultOptions, options);`
```
givenOptions = { context: {} }
options = { context: {} }
```

**Comment by nicolaslopezj** [comment]
You're right, now it's working correctly

**Pull request closed without merging**
